//
// Created by Nolan on 11/21/2022.
//

#ifndef INC_594_LONGEST_HARMONIOUS_SUBSEQUENCE_MAIN_H
#define INC_594_LONGEST_HARMONIOUS_SUBSEQUENCE_MAIN_H


class main {

};


#endif //INC_594_LONGEST_HARMONIOUS_SUBSEQUENCE_MAIN_H
